// penwright:generated-style — edit via Settings → Style
//
// Generated by Penwright. Values live in `.penwright/style.json` and can
// be edited via the Design sidebar tab. Manual edits to the fenced
// `penwright:custom` block at the bottom of `apply-style` are preserved
// across regenerations.
//
// Usage from main.typ:
//   #import "style.typ": *
//   #show: apply-style
//
// `#import` brings `style-colors` into scope so body content can
// reference the palette directly; `#show: apply-style` applies all
// the generated set/show rules to the rest of the document.

#let style-colors = (
  primary:    rgb("#20292a"),
  accent:     rgb("#4a6b62"),
  text:       rgb("#20292a"),
  background: rgb("#eef0ec"),
  muted:      rgb("#7c847e"),
)

#let style-fonts = (
  body:    "Crimson Pro",
  heading: "Spectral",
  code:    "IBM Plex Mono",
)

#let style-bleed = 0mm

#let _credit-sep   = " — "
#let _credit-label = "Photo: "
#let figure-caption-credit(caption, credit) = [#caption#text(style: "italic", fill: style-colors.muted)[#_credit-sep#_credit-label#credit]]

#let chapter-name() = context {
  let here-loc = here()
  let chapters = query(heading.where(level: 1)).filter(it => it.location().page() <= here-loc.page())
  if chapters.len() > 0 { chapters.last().body } else { [] }
}
#let section-name() = context {
  let here-loc = here()
  let sections = query(heading.where(level: 2)).filter(it => it.location().page() <= here-loc.page())
  if sections.len() > 0 { sections.last().body } else { [] }
}

#let apply-style(body) = {
  set page(paper: "a4", margin: 3.4cm, fill: style-colors.background, numbering: "1", header: [#text(size: 0.74em, tracking: 0.14em, fill: style-colors.muted)[MAGAZINE] #h(1fr) #text(size: 0.74em, tracking: 0.14em, fill: style-colors.muted)[ISSUE 01 · 2026]])
  set text(font: "Crimson Pro", size: 12pt, fill: style-colors.text)
  set par(leading: 0.65em, first-line-indent: 1.1em)
  show raw: set text(font: "IBM Plex Mono")

  show heading.where(level: 1): set text(font: "Spectral", size: 27pt, weight: "semibold", fill: style-colors.text)
  show heading.where(level: 1): it => block(above: 0.2em, it)
  show heading.where(level: 2): set text(font: "Spectral", size: 13pt, weight: "bold", fill: style-colors.accent)
  show heading.where(level: 2): it => block(above: 1.4em, it)
  show heading.where(level: 3): set text(font: "Spectral", size: 12pt, weight: "semibold", fill: style-colors.text)
  show heading.where(level: 3): it => block(above: 1em, it)
  show heading.where(level: 4): set text(font: "Spectral", size: 11pt, weight: "semibold", fill: style-colors.text)
  show heading.where(level: 4): it => block(above: 1em, it)
  show heading.where(level: 5): set text(font: "Spectral", size: 11pt, weight: "bold", fill: style-colors.text)
  show heading.where(level: 5): it => block(above: 0.9em, it)
  show heading.where(level: 6): set text(font: "Spectral", size: 10pt, weight: "bold", fill: style-colors.muted)
  show heading.where(level: 6): it => block(above: 0.8em, it)

  show quote.where(block: true): it => block(stroke: (left: 3pt + style-colors.accent), inset: (left: 1em, top: 0.4em, bottom: 0.4em), text(fill: style-colors.text, style: "italic", it.body))
  show raw.where(block: true): it => block(width: 100%, fill: luma(245), radius: 4pt, inset: (x: 1em, y: 0.6em), it)
  set figure.caption(position: bottom, separator: ": ")
  show figure.caption: it => align(left, text(size: 9pt, fill: style-colors.muted, it))
  set table(stroke: 0.5pt + style-colors.muted, inset: 6pt, fill: (col, row) => if row == 0 { style-colors.primary } else { none })
  show table.cell.where(y: 0): it => text(fill: style-colors.background, weight: "bold", it.body)

  // ─── penwright:custom — your free-form Typst goes here ───
  // Asymmetric type area: narrow gutter, wide outer margin (calm, editorial).
  set page(margin: (left: 3.4cm, right: 5.2cm, top: 3cm, bottom: 3.2cm))
  set par(justify: true)
  set figure(numbering: none)
  show heading: set text(hyphenate: false)
  // Quiet, uniform table of contents — every entry the same size.
  show outline.entry: it => { set text(size: 10.5pt, fill: style-colors.text, weight: "regular"); it }
  show link: it => text(fill: style-colors.accent, it)
  // ─── penwright:custom-end ───

  body
}

// Section style "Feature" — opt in from a chapter file with:
//   #import "../style.typ": feature-style
//   #show: feature-style
#let feature-style(body) = {
  set page(columns: 1)
  set text(font: "Spectral", size: 12pt, fill: rgb("#20292a"))
  set par(leading: 0.72em, first-line-indent: 1.1em)
  show raw: set text(font: "IBM Plex Mono")

  show heading.where(level: 1): set text(font: "Spectral", size: 34pt, weight: "bold", fill: rgb("#b07a45"))
  show heading.where(level: 1): it => block(above: 0.2em, it)
  show heading.where(level: 2): set text(font: "Spectral", size: 18pt, weight: "semibold", fill: rgb("#20292a"))
  show heading.where(level: 2): it => block(above: 1.4em, it)
  show heading.where(level: 3): set text(font: "Spectral", size: 12pt, weight: "semibold", fill: rgb("#20292a"))
  show heading.where(level: 3): it => block(above: 1em, it)
  show heading.where(level: 4): set text(font: "Spectral", size: 11pt, weight: "semibold", fill: rgb("#20292a"))
  show heading.where(level: 4): it => block(above: 1em, it)
  show heading.where(level: 5): set text(font: "Spectral", size: 11pt, weight: "bold", fill: rgb("#20292a"))
  show heading.where(level: 5): it => block(above: 0.9em, it)
  show heading.where(level: 6): set text(font: "Spectral", size: 10pt, weight: "bold", fill: rgb("#7c847e"))
  show heading.where(level: 6): it => block(above: 0.8em, it)

  show quote.where(block: true): it => block(stroke: (left: 3pt + rgb("#b07a45")), inset: (left: 1em, top: 0.4em, bottom: 0.4em), text(fill: rgb("#20292a"), style: "italic", it.body))
  show raw.where(block: true): it => block(width: 100%, fill: luma(245), radius: 4pt, inset: (x: 1em, y: 0.6em), it)
  set figure.caption(position: bottom, separator: ": ")
  show figure.caption: it => align(left, text(size: 9pt, fill: rgb("#7c847e"), it))
  set table(stroke: 0.5pt + rgb("#7c847e"), inset: 6pt, fill: (col, row) => if row == 0 { rgb("#20292a") } else { none })
  show table.cell.where(y: 0): it => text(fill: rgb("#eef0ec"), weight: "bold", it.body)

  body
}

// Section style "Interview" — opt in from a chapter file with:
//   #import "../style.typ": interview-style
//   #show: interview-style
#let interview-style(body) = {
  set page(columns: 2)
  set text(font: "IBM Plex Sans", size: 10pt, fill: rgb("#20292a"))
  set par(leading: 0.65em, first-line-indent: 1.1em)
  show raw: set text(font: "IBM Plex Mono")

  show heading.where(level: 1): set text(font: "IBM Plex Sans", size: 24pt, weight: "bold", fill: rgb("#3f6470"))
  show heading.where(level: 1): it => block(above: 0.2em, it)
  show heading.where(level: 2): set text(font: "IBM Plex Sans", size: 13pt, weight: "bold", fill: rgb("#3f6470"))
  show heading.where(level: 2): it => block(above: 1.4em, it)
  show heading.where(level: 3): set text(font: "IBM Plex Sans", size: 12pt, weight: "semibold", fill: rgb("#20292a"))
  show heading.where(level: 3): it => block(above: 1em, it)
  show heading.where(level: 4): set text(font: "IBM Plex Sans", size: 11pt, weight: "semibold", fill: rgb("#20292a"))
  show heading.where(level: 4): it => block(above: 1em, it)
  show heading.where(level: 5): set text(font: "IBM Plex Sans", size: 11pt, weight: "bold", fill: rgb("#20292a"))
  show heading.where(level: 5): it => block(above: 0.9em, it)
  show heading.where(level: 6): set text(font: "IBM Plex Sans", size: 10pt, weight: "bold", fill: rgb("#7c847e"))
  show heading.where(level: 6): it => block(above: 0.8em, it)

  show quote.where(block: true): it => block(stroke: (left: 3pt + rgb("#3f6470")), inset: (left: 1em, top: 0.4em, bottom: 0.4em), text(fill: rgb("#20292a"), style: "italic", it.body))
  show raw.where(block: true): it => block(width: 100%, fill: luma(245), radius: 4pt, inset: (x: 1em, y: 0.6em), it)
  set figure.caption(position: bottom, separator: ": ")
  show figure.caption: it => align(left, text(size: 9pt, fill: rgb("#7c847e"), it))
  set table(stroke: 0.5pt + rgb("#7c847e"), inset: 6pt, fill: (col, row) => if row == 0 { rgb("#20292a") } else { none })
  show table.cell.where(y: 0): it => text(fill: rgb("#eef0ec"), weight: "bold", it.body)

  body
}

// Section style "Essay" — opt in from a chapter file with:
//   #import "../style.typ": essay-style
//   #show: essay-style
#let essay-style(body) = {
  set page(columns: 1)
  set text(font: "Crimson Pro", size: 12pt, fill: rgb("#20292a"))
  set par(leading: 0.85em, first-line-indent: 1.1em)
  show raw: set text(font: "IBM Plex Mono")

  show heading.where(level: 1): set text(font: "Crimson Pro", size: 26pt, weight: "medium", fill: rgb("#20292a"))
  show heading.where(level: 1): it => block(above: 0.4em, it)
  show heading.where(level: 2): set text(font: "Crimson Pro", size: 15pt, weight: "semibold", fill: rgb("#20292a"))
  show heading.where(level: 2): it => block(above: 1.4em, it)
  show heading.where(level: 3): set text(font: "Crimson Pro", size: 12pt, weight: "semibold", fill: rgb("#20292a"))
  show heading.where(level: 3): it => block(above: 1em, it)
  show heading.where(level: 4): set text(font: "Crimson Pro", size: 11pt, weight: "semibold", fill: rgb("#20292a"))
  show heading.where(level: 4): it => block(above: 1em, it)
  show heading.where(level: 5): set text(font: "Crimson Pro", size: 11pt, weight: "bold", fill: rgb("#20292a"))
  show heading.where(level: 5): it => block(above: 0.9em, it)
  show heading.where(level: 6): set text(font: "Crimson Pro", size: 10pt, weight: "bold", fill: rgb("#7c847e"))
  show heading.where(level: 6): it => block(above: 0.8em, it)

  show quote.where(block: true): it => block(stroke: (left: 3pt + rgb("#6e7460")), inset: (left: 1em, top: 0.4em, bottom: 0.4em), text(fill: rgb("#20292a"), style: "italic", it.body))
  show raw.where(block: true): it => block(width: 100%, fill: luma(245), radius: 4pt, inset: (x: 1em, y: 0.6em), it)
  set figure.caption(position: bottom, separator: ": ")
  show figure.caption: it => align(left, text(size: 9pt, fill: rgb("#7c847e"), it))
  set table(stroke: 0.5pt + rgb("#7c847e"), inset: 6pt, fill: (col, row) => if row == 0 { rgb("#20292a") } else { none })
  show table.cell.where(y: 0): it => text(fill: rgb("#eef0ec"), weight: "bold", it.body)

  body
}

// Section style "Photo Essay" — opt in from a chapter file with:
//   #import "../style.typ": photo-essay-style
//   #show: photo-essay-style
#let photo-essay-style(body) = {
  set page(columns: 1)
  set text(font: "Inter", size: 12pt, fill: rgb("#20292a"))
  set par(leading: 0.65em, first-line-indent: 1.1em)
  show raw: set text(font: "IBM Plex Mono")

  show heading.where(level: 1): set text(font: "Inter", size: 40pt, weight: "bold", fill: rgb("#20292a"))
  show heading.where(level: 1): it => block(above: 0.2em, it)
  show heading.where(level: 2): set text(font: "Inter", size: 14pt, weight: "semibold", fill: rgb("#7c847e"))
  show heading.where(level: 2): it => block(above: 1.4em, it)
  show heading.where(level: 3): set text(font: "Inter", size: 12pt, weight: "semibold", fill: rgb("#20292a"))
  show heading.where(level: 3): it => block(above: 1em, it)
  show heading.where(level: 4): set text(font: "Inter", size: 11pt, weight: "semibold", fill: rgb("#20292a"))
  show heading.where(level: 4): it => block(above: 1em, it)
  show heading.where(level: 5): set text(font: "Inter", size: 11pt, weight: "bold", fill: rgb("#20292a"))
  show heading.where(level: 5): it => block(above: 0.9em, it)
  show heading.where(level: 6): set text(font: "Inter", size: 10pt, weight: "bold", fill: rgb("#7c847e"))
  show heading.where(level: 6): it => block(above: 0.8em, it)

  show quote.where(block: true): it => block(stroke: (left: 3pt + rgb("#232a26")), inset: (left: 1em, top: 0.4em, bottom: 0.4em), text(fill: rgb("#20292a"), style: "italic", it.body))
  show raw.where(block: true): it => block(width: 100%, fill: luma(245), radius: 4pt, inset: (x: 1em, y: 0.6em), it)
  set figure.caption(position: bottom, separator: ": ")
  show figure.caption: it => align(left, text(size: 9pt, fill: rgb("#7c847e"), it))
  set table(stroke: 0.5pt + rgb("#7c847e"), inset: 6pt, fill: (col, row) => if row == 0 { rgb("#20292a") } else { none })
  show table.cell.where(y: 0): it => text(fill: rgb("#eef0ec"), weight: "bold", it.body)

  body
}

// Section style "Department" — opt in from a chapter file with:
//   #import "../style.typ": department-style
//   #show: department-style
#let department-style(body) = {
  set page(columns: 3)
  set text(font: "IBM Plex Sans", size: 9pt, fill: rgb("#20292a"))
  set par(leading: 0.65em, first-line-indent: 1.1em)
  show raw: set text(font: "IBM Plex Mono")

  show heading.where(level: 1): set text(font: "IBM Plex Sans", size: 16pt, weight: "bold", fill: rgb("#7a5650"))
  show heading.where(level: 1): it => block(above: 0.2em, it)
  show heading.where(level: 2): set text(font: "IBM Plex Sans", size: 11pt, weight: "bold", fill: rgb("#7a5650"))
  show heading.where(level: 2): it => block(above: 1.4em, it)
  show heading.where(level: 3): set text(font: "IBM Plex Sans", size: 12pt, weight: "semibold", fill: rgb("#20292a"))
  show heading.where(level: 3): it => block(above: 1em, it)
  show heading.where(level: 4): set text(font: "IBM Plex Sans", size: 11pt, weight: "semibold", fill: rgb("#20292a"))
  show heading.where(level: 4): it => block(above: 1em, it)
  show heading.where(level: 5): set text(font: "IBM Plex Sans", size: 11pt, weight: "bold", fill: rgb("#20292a"))
  show heading.where(level: 5): it => block(above: 0.9em, it)
  show heading.where(level: 6): set text(font: "IBM Plex Sans", size: 10pt, weight: "bold", fill: rgb("#7c847e"))
  show heading.where(level: 6): it => block(above: 0.8em, it)

  show quote.where(block: true): it => block(stroke: (left: 3pt + rgb("#7a5650")), inset: (left: 1em, top: 0.4em, bottom: 0.4em), text(fill: rgb("#20292a"), style: "italic", it.body))
  show raw.where(block: true): it => block(width: 100%, fill: luma(245), radius: 4pt, inset: (x: 1em, y: 0.6em), it)
  set figure.caption(position: bottom, separator: ": ")
  show figure.caption: it => align(left, text(size: 9pt, fill: rgb("#7c847e"), it))
  set table(stroke: 0.5pt + rgb("#7c847e"), inset: 6pt, fill: (col, row) => if row == 0 { rgb("#20292a") } else { none })
  show table.cell.where(y: 0): it => text(fill: rgb("#eef0ec"), weight: "bold", it.body)

  body
}
