// vswrite:generated-style — edit via Settings → Style
//
// Generated by vswrite. Values live in `.vswrite/style.json` and can
// be edited via the Design sidebar tab. Manual edits to the fenced
// `vswrite:custom` block at the bottom of `apply-style` are preserved
// across regenerations.
//
// Usage from main.typ:
//   #import "style.typ": *
//   #show: apply-style
//
// `#import` brings `style-colors` into scope so body content can
// reference the palette directly; `#show: apply-style` applies all
// the generated set/show rules to the rest of the document.

#let style-colors = (
  primary:    rgb("#1e293b"),
  accent:     rgb("#7c1d1d"),
  text:       rgb("#0f172a"),
  background: rgb("#ffffff"),
  muted:      rgb("#64748b"),
)

#let apply-style(body) = {
  set page(paper: "a4", margin: 2.5cm, fill: style-colors.background, numbering: "1")
  set text(font: "Crimson Pro", size: 11pt, fill: style-colors.text)
  set par(leading: 0.65em, spacing: 1.2em, first-line-indent: 1em)
  show raw: set text(font: "IBM Plex Mono")

  set heading(numbering: "1.1")
  show heading.where(level: 1): set text(font: "IBM Plex Sans", size: 22pt, weight: "bold", fill: style-colors.primary)
  show heading.where(level: 1): it => block(above: 1.8em, it)
  show heading.where(level: 2): set text(font: "IBM Plex Sans", size: 16pt, weight: "semibold", fill: style-colors.primary)
  show heading.where(level: 2): it => block(above: 1.4em, it)
  show heading.where(level: 3): set text(font: "IBM Plex Sans", size: 13pt, weight: "semibold", fill: style-colors.primary)
  show heading.where(level: 3): it => block(above: 1.1em, it)
  show heading.where(level: 4): set text(font: "IBM Plex Sans", size: 12pt, weight: "semibold", fill: style-colors.text)
  show heading.where(level: 4): it => block(above: 1em, it)
  show heading.where(level: 5): set text(font: "IBM Plex Sans", size: 11pt, weight: "bold", fill: style-colors.text)
  show heading.where(level: 5): it => block(above: 0.9em, it)
  show heading.where(level: 6): set text(font: "IBM Plex Sans", size: 10pt, weight: "bold", fill: style-colors.muted)
  show heading.where(level: 6): it => block(above: 0.8em, it)

  show quote.where(block: true): it => block(stroke: (left: 3pt + style-colors.accent), inset: (left: 1em, top: 0.4em, bottom: 0.4em), text(fill: style-colors.text, style: "italic", it.body))
  show raw.where(block: true): it => block(width: 100%, fill: luma(245), radius: 4pt, inset: (x: 1em, y: 0.6em), it)
  set figure.caption(position: bottom, separator: ": ")
  show figure.caption: it => align(left, text(size: 9pt, fill: style-colors.muted, it))
  set table(stroke: 0.5pt + style-colors.muted, inset: 6pt, fill: (col, row) => if row == 0 { style-colors.primary } else { none })
  show table.cell.where(y: 0): it => text(fill: style-colors.background, weight: "bold", it.body)

  // ─── vswrite:custom — your free-form Typst goes here ───
  // Numbering for elements the Designer doesn't expose yet.
  set math.equation(numbering: "(1)")
  set figure(numbering: "1")
  
  // Make external links visibly linkable.
  show link: it => underline(text(fill: blue.darken(20%), it))
  // ─── vswrite:custom-end ───

  body
}
