/**
 * Style Parser — JSON ↔ Typst preamble.
 *
 * Forward direction (`generateStyleTypst`) is the load-bearing one: it takes
 * a `ProjectStyle` and emits the contents of `<project>/style.typ`. The file
 * is `#include`d from `main.typ`, so the `#set` and `#show` rules apply to
 * the whole document.
 *
 * Reverse direction (`detectStylePreambleConflicts`) is best-effort and only
 * used for the migration warning: it scans the top of a Typst file for
 * `#set text(...)`, `#set page(...)`, `#set par(...)` blocks that would
 * silently override style.typ's rules, and lists them for the user.
 *
 * Generation rules (kept simple on purpose for Phase A):
 *  - one `#set` per concern
 *  - colors exposed as a `style-colors` dict so future skills / MCP tools
 *    can reference the palette by name without re-parsing this file
 *  - explanatory header comment so users opening style.typ understand it
 */

import { ProjectStyle } from './styleTypes';

/** Marker line at top of generated style.typ — used to detect ownership. */
export const STYLE_TYPST_MARKER = '// vswrite:generated-style — edit via Settings → Style';

/** Marker we look for in root .typ files to know style.typ is already wired. */
export const STYLE_INCLUDE_LINE = '#include "style.typ"';

/**
 * Quotes a font name for Typst. Phase A keeps this single-string — Typst's
 * `text(font: ...)` accepts a tuple for explicit fallbacks (e.g.
 * `("Inter", "Helvetica")`), but CSS-style generic-family aliases like
 * "serif" / "sans-serif" do NOT exist in Typst and emit a warning, so we
 * deliberately don't synthesize them. Phase B will expose a multi-font
 * picker.
 */
function fontLiteral(name: string): string {
  const safe = name.replace(/"/g, '\\"');
  return `"${safe}"`;
}

/**
 * Converts an arbitrary hex color (#rgb or #rrggbb, case-insensitive) into
 * a Typst rgb literal. Falls back to white on parse failure — the schema
 * sanitizer already restricts inputs to hex, so this is defensive.
 */
function colorLiteral(hex: string): string {
  const m = hex.trim().match(/^#([0-9a-f]{3}|[0-9a-f]{6})$/i);
  if (!m) return 'rgb("#ffffff")';
  let value = m[1];
  if (value.length === 3) {
    value = value.split('').map(c => c + c).join('');
  }
  return `rgb("#${value.toLowerCase()}")`;
}

export function generateStyleTypst(style: ProjectStyle): string {
  const lines: string[] = [];
  const push = (s: string = '') => lines.push(s);

  push(STYLE_TYPST_MARKER);
  push('//');
  push('// This file is generated by vswrite. The values live in');
  push('// .vswrite/style.json and can be edited via the Settings dialog.');
  push('// Manual edits here are preserved until you save Settings again.');
  push();

  // ─── Palette ───
  push('#let style-colors = (');
  push(`  primary:    ${colorLiteral(style.colors.primary)},`);
  push(`  accent:     ${colorLiteral(style.colors.accent)},`);
  push(`  text:       ${colorLiteral(style.colors.text)},`);
  push(`  background: ${colorLiteral(style.colors.background)},`);
  push(`  muted:      ${colorLiteral(style.colors.muted)},`);
  push(')');
  push();

  // ─── Page ───
  const pageProps: string[] = [
    `paper: "${style.layout.paper}"`,
    `margin: ${style.layout.margin}`,
    `fill: style-colors.background`,
  ];
  if (style.layout.columns > 1) pageProps.push(`columns: ${style.layout.columns}`);
  push(`#set page(${pageProps.join(', ')})`);

  // ─── Text ───
  push(`#set text(font: ${fontLiteral(style.fonts.body)}, size: ${style.scale.base}, fill: style-colors.text)`);

  // ─── Paragraph ───
  push(`#set par(leading: ${style.scale.leading})`);

  // ─── Code / raw ───
  push(`#show raw: set text(font: ${fontLiteral(style.fonts.code)})`);
  push();

  // ─── Headings ───
  for (const [levelName, level] of [['h1', 1], ['h2', 2]] as const) {
    const h = style.headings[levelName];
    push(`#show heading.where(level: ${level}): set text(font: ${fontLiteral(style.fonts.heading)}, size: ${h.size}, weight: "${h.weight}", fill: style-colors.${h.color})`);
    push(`#show heading.where(level: ${level}): it => block(above: ${h.marginTop}, it)`);
  }
  push();

  return lines.join('\n');
}

/**
 * Scans the start of a Typst document for `#set text|page|par(...)` calls
 * that would override the rules from `style.typ`. Returns a list of human-
 * readable findings used by the migration warning dialog.
 *
 * Heuristic only: we stop scanning at the first non-preamble line (heading,
 * content) to avoid flagging legitimate inline rules inside the body.
 */
export function detectStylePreambleConflicts(rootFileContents: string): string[] {
  if (rootFileContents.includes(STYLE_INCLUDE_LINE)) return [];

  const findings: string[] = [];
  const lines = rootFileContents.split(/\r?\n/);
  let braceDepth = 0;
  let i = 0;

  while (i < lines.length) {
    const raw = lines[i];
    const line = raw.trim();

    if (braceDepth > 0) {
      for (const ch of raw) {
        if (ch === '{' || ch === '(' || ch === '[') braceDepth++;
        if (ch === '}' || ch === ')' || ch === ']') braceDepth--;
      }
      i++;
      continue;
    }

    if (line === '' || line.startsWith('//')) { i++; continue; }

    if (
      line.startsWith('#set text(') ||
      line.startsWith('#set page(') ||
      line.startsWith('#set par(') ||
      line.startsWith('#set heading(') ||
      line.startsWith('#show heading')
    ) {
      findings.push(line.length > 80 ? line.slice(0, 77) + '…' : line);
      for (const ch of raw) {
        if (ch === '{' || ch === '(' || ch === '[') braceDepth++;
        if (ch === '}' || ch === ')' || ch === ']') braceDepth--;
      }
      i++;
      continue;
    }

    // Other preamble lines (#import / #let) — skip without flagging.
    if (line.startsWith('#import ') || line.startsWith('#let ') || line.startsWith('#set ') || line.startsWith('#show ')) {
      i++;
      continue;
    }

    // Reached body content — stop.
    break;
  }

  return findings;
}

/**
 * Returns root-file contents with `#include "style.typ"` ensured at the top.
 * If the include already exists anywhere, returns the input unchanged.
 *
 * Skipped lines at the very top:
 *  - shebang-style comments (`// …`) — left alone, include goes below them
 *  - blank lines — same
 * This keeps user-authored top-of-file notes intact.
 */
export function ensureStyleInclude(rootFileContents: string): string {
  if (rootFileContents.includes(STYLE_INCLUDE_LINE)) return rootFileContents;

  const lines = rootFileContents.split(/\r?\n/);
  let insertAt = 0;
  while (insertAt < lines.length) {
    const t = lines[insertAt].trim();
    if (t === '' || t.startsWith('//')) { insertAt++; continue; }
    break;
  }

  const before = lines.slice(0, insertAt);
  const after = lines.slice(insertAt);
  const prefix = before.length > 0 && before[before.length - 1] !== '' ? [...before, ''] : before;
  const suffix = after.length > 0 && after[0] !== '' ? ['', ...after] : after;
  return [...prefix, STYLE_INCLUDE_LINE, ...suffix].join('\n');
}
