// penwright:generated-style — edit via Settings → Style
//
// Generated by Penwright. Values live in `.penwright/style.json` and can
// be edited via the Design sidebar tab. Manual edits to the fenced
// `penwright:custom` block at the bottom of `apply-style` are preserved
// across regenerations.
//
// Usage from main.typ:
//   #import "style.typ": *
//   #show: apply-style
//
// `#import` brings `style-colors` into scope so body content can
// reference the palette directly; `#show: apply-style` applies all
// the generated set/show rules to the rest of the document.

#let style-colors = (
  primary:    rgb("#7c2d12"),
  accent:     rgb("#d97706"),
  text:       rgb("#3f2d16"),
  background: rgb("#fdf6e3"),
  muted:      rgb("#8a7a52"),
)

#let style-fonts = (
  body:    "Spectral",
  heading: "Spectral",
  code:    "IBM Plex Mono",
)

#let style-bleed = 0mm

#let _credit-sep   = " — "
#let _credit-label = "Photo: "
#let figure-caption-credit(caption, credit) = [#caption#text(style: "italic", fill: style-colors.muted)[#_credit-sep#_credit-label#credit]]

#let chapter-name() = context {
  let here-loc = here()
  let chapters = query(heading.where(level: 1)).filter(it => it.location().page() <= here-loc.page())
  if chapters.len() > 0 { chapters.last().body } else { [] }
}
#let section-name() = context {
  let here-loc = here()
  let sections = query(heading.where(level: 2)).filter(it => it.location().page() <= here-loc.page())
  if sections.len() > 0 { sections.last().body } else { [] }
}

#let apply-style(body) = {
  set page(paper: "a4", margin: 2.5cm, fill: style-colors.background)
  set text(font: "Spectral", size: 10pt, fill: style-colors.text)
  set par(leading: 0.66em, spacing: 0.7em, first-line-indent: 0pt)
  show raw: set text(font: "IBM Plex Mono")

  show heading.where(level: 1): set text(font: "Spectral", size: 24pt, weight: "bold", fill: style-colors.primary)
  show heading.where(level: 1): it => block(above: 2em, it)
  show heading.where(level: 2): set text(font: "Spectral", size: 18pt, weight: "semibold", fill: style-colors.primary)
  show heading.where(level: 2): it => block(above: 1.6em, it)
  show heading.where(level: 3): set text(font: "Spectral", size: 14pt, weight: "semibold", fill: style-colors.primary)
  show heading.where(level: 3): it => block(above: 1.3em, it)
  show heading.where(level: 4): set text(font: "Spectral", size: 12pt, weight: "semibold", fill: style-colors.text)
  show heading.where(level: 4): it => block(above: 1.1em, it)
  show heading.where(level: 5): set text(font: "Spectral", size: 11pt, weight: "bold", fill: style-colors.text)
  show heading.where(level: 5): it => block(above: 1em, it)
  show heading.where(level: 6): set text(font: "Spectral", size: 10pt, weight: "bold", fill: style-colors.muted)
  show heading.where(level: 6): it => block(above: 0.8em, it)

  show quote.where(block: true): it => block(stroke: (left: 3pt + style-colors.accent), inset: (left: 1em, top: 0.4em, bottom: 0.4em), text(fill: style-colors.text, style: "italic", it.body))
  show raw.where(block: true): it => block(width: 100%, fill: luma(245), radius: 4pt, inset: (x: 1em, y: 0.6em), it)
  set figure.caption(position: bottom, separator: ": ")
  show figure.caption: it => align(left, text(size: 9pt, fill: style-colors.muted, it))
  set table(stroke: 0.5pt + style-colors.muted, inset: 6pt, fill: (col, row) => if row == 0 { style-colors.primary } else { none })
  show table.cell.where(y: 0): it => text(fill: style-colors.background, weight: "bold", it.body)

  // ─── penwright:custom — your free-form Typst goes here ───
  show heading: it => block(above: 1.1em, below: 0.6em)[#it.body #v(-0.15em) #line(length: 1.4cm, stroke: 3pt + style-colors.accent)]
  // ─── penwright:custom-end ───

  body
}
